### ISSUE TITLE
car wheels

### ISSUE THREAD

**Issue by JekSun97** [appsinacup/godot-softbody2d#11]
Is it possible to somehow make a car with wheels like in the jelly car game?

**Comment by Ughuuu** [comment]
Sure should be possible, yes. I think you can make 2 softbodies, then attach the softbodies to something else using joints. I'll see and try to add a tutorial for this on current page for tutorials: https://softbody2d.appsinacup.com/docs/category/tutorial

**Comment by Ughuuu** [comment]
I think I will make 2 tutorials, how to connect a character controller with the softbody and make it move, and how to connect a softbody to other objects.

**Comment by Ughuuu** [comment]
Ok, check this: https://softbody2d.appsinacup.com/docs/tutorial-basics/attach-a-softbody-to-character-controller

Making a car should be similar to this, though probably you want to rotate the wheels instead of just moving the whole thing.

**Comment by Ughuuu** [comment]
Eh, added a car demo also to the tutorials: https://softbody2d.appsinacup.com/docs/tutorial-basics/make-a-car/

Enjoy
