### ISSUE TITLE
A lot of errors from skeleton modifications

### ISSUE THREAD

**Issue by Ughuuu** [appsinacup/godot-softbody2d#3]
Right now, you will see errors like this:

```
Bone2D node cache is out of date. Attempting to update...
```

There is already an open issue on godot repo: https://github.com/godotengine/godot/issues/73247

**Comment by Ughuuu** [comment]
Should be fixed in godot 4.3. The linked issue was closed.

**Comment by ScriptlessWeek** [comment]
Is this the same issue? I'm using 4.2.2 on linux mint with a fresh project.
I get this error when I run a scene with the softbody2d using icon.svg with no modifications.
![Screenshot at 2024-07-17 15-42-43](https://github.com/user-attachments/assets/bf4aea30-c9e8-43a6-b02c-6271b54ae958)
Then at the very end I also have this
![Screenshot at 2024-07-17 15-43-49](https://github.com/user-attachments/assets/7b7f0b9d-b47d-468a-9ba4-f475693bae70)

**Comment by Ughuuu** [comment]
It is usable, before 4.3 there is a warning, harmless. After 4.3 the warning doesn't spam anymore. If anything the warning just might affect performance a bit(because its logging so much)

**Comment by ScriptlessWeek** [comment]
Thanks for the info, much appreciated.
