### ISSUE TITLE
Error while loading from nested scenes. bones array is empty.

### ISSUE THREAD

**Issue by nelsonayamashita** [appsinacup/godot-softbody2d#5]
Maybe related to [godotengine/godot#73247](https://github.com/godotengine/godot/issues/73247) and #3.

Steps to reproduce:
- Install the SoftBody2D node plugin from the asset lib.
- Create a SoftBody2D with any texture.
- Create a "World" scene. Add a Node2D as root and then instantiate the previously created SoftBody as a child scene.
- Create a "Main" scene. Add a node as root, then add the previously created "World" scene as a child scene.
- Execute the Main scene, it'll probably run fine.
- Go to Project -> Reload Current Project
- Execute the Main scene again.

A `Out of bounds get index '0' (on base: 'Array[Node]')` error will appear, saying that the line with 
```GDScript
softbodyrb.bone = bones.filter(func(bone): return bone.name == child.name)[0]
``` 
Caused the error, which is strange, since in the debugger the `bones` array appears to be populated...

My current workaround is to delete the World scene from the Main scene and add a script to the Main scene that adds the World scene via code:

```GDScript
extends Control

var path_to_level := preload("res://world.tscn")

func _ready() -> void:
	var next_level = path_to_level.instantiate()
	add_child(next_level)
```
I believe this is related to the way Godot is having problems with how bones are being cached and loading them, so I don't think this can be easily fixed within the plugin. But the workaround might help someone also facing the problem.

**Minimal reproduction project**

[Soft-Body-Issue.zip](https://github.com/appsinacup/godot-softbody2d/files/12969466/Soft-Body-Issue.zip)

**Steps to reproduce the issue in the MRP**

- Download zip file and extract the project
- Open the project in Godot and run the main scene
- Should throw the same error as described above

**Comment by Ughuuu** [comment]
Hm, sorry for late respond. I'm checking it now, but it does seem weird error, at least I never saw it happen.

**Comment by nelsonayamashita** [comment]
Hey, no problem! Thanks for checking the issue.
I've re-uploaded the file in the OP, let me know if it's working now.

**Comment by Ughuuu** [comment]
Seems to be the plugin tries to recreate the softbody even if there aren't any changes in it. Will try to fix so it doesn't happen(eg. add a dirty state if there is such a thing).

**Comment by Ughuuu** [comment]
Seems to no longer occur in 4.3
