### ISSUE TITLE
Can't apply external force

### ISSUE THREAD

**Issue by MrJox** [appsinacup/godot-softbody2d#8]
Hi, I cannot apply an external force to the softbody.
The softbody itself behaves exactly how I want it - it's a soft circular blob.

Now I want to fire at that blob and make it react. How can I achieve it? 
Functions such as apply_impulse() don't work

**Comment by Ughuuu** [comment]
Hi.
The softbody itself contains a lot of rigidbodies. I could provide a function that applies impulse on all of them, but I'm not sure thats whats expected.
You van try getting all rigidbodies children and try some logic. You can also get the center rigidbody and move that.

**Comment by MrJox** [comment]
As I'm a little newbie in this I would love to see an example or two

**Comment by Ughuuu** [comment]
Ill try to add one when i have some time. What is ur use case though? What are you expecting to happen in your game? How do you want to move the softbody?

**Comment by MrJox** [comment]
I want to shoot at the softbody blob, make it have a visual impact in place of collision, as well as change the blob's position in the direction of the shooting

**Comment by Ughuuu** [comment]
Can you provide also an image or something of what you want? Or if you find in an example somewhere or if you can replicate with a rigidbody.

**Comment by MrJox** [comment]
![image](https://github.com/appsinacup/godot-softbody2d/assets/22772586/92a8487f-21cb-4511-bb43-e1429dbe2eb4)

So roughly, here's the idea:
1. Imagine a balloon, filled with water. It stays in a resting state
2. An external force is applied to the left of balloon with the force direction Vector2(+1, 0). Example: balloon was kicked or shoot with a rubber bullet.
3. Balloon is moved to the right, as an impact of a force applied to it's left corner
4. Balloon returns to a resting state

**Comment by Ughuuu** [comment]
Interesting. And is this not what happens when you hit the softbody right now? That would be what I would expect to happen without needing to apply any force to it.

**Comment by MrJox** [comment]
I fire bullets at it and push myself against the softbody, however it has no effect. The physics work only with gravity. Maybe I'm missing something in my setup though.

The softbody is setup this way:
Node2D (root node)
-- SoftBody2D (texture is provided, bones are present)

If I simply drop the body from air against a surface, it works exactly as it should. But the problem is I don't understand how to apply external forces to it, like an impulse to the side

**Comment by Ughuuu** [comment]
Can you provide an example project or a video?

**Comment by Ughuuu** [comment]
A test project where you hit a softbody and it doesnt move. In my tests the softbody moves if it gets hit by another body, even if gravity is 0.

**Comment by MrJox** [comment]
Where can I see you project? It may help me understand what I'm missing

**Comment by Ughuuu** [comment]
Not unless you get all rigidbodies and check which one is closest.

**Comment by Ughuuu** [comment]
I'm adding now some new samples for your use case though.

**Comment by MrJox** [comment]
Thank you very much!

**Comment by MrJox** [comment]
Meanwhile I did a few more tests myself - I created a softbody (its just a solid circle texture) with the following parameters:
Vertex interval - 173
Radius - 10
Total Mass - 10
Shape Type - CIrcle
Joint type - pin
No physics material override
Texture size is 512x512

![image](https://github.com/appsinacup/godot-softbody2d/assets/22772586/e5c678a9-cc22-464d-bf4e-6691219af2ec)

Scene hierarchy is the following:
CharacterBody2D (Root)
-- SoftBody2D
-- RigidBody2D (for bullet collision test)
---- CollisionShape2D
-- StaticBody2D (for ground collision test)
---- CollisionShape2D

CharacterBody2D node transform is scaled down to 0.1 on both axes.

The idea was to test how the softbody reacts to collision against an external force - a bullet that hits the softbody from horizontal direction. I set bullet mass to a ridiculous number (1000000 kg). The softbody mass is 10 kg. The bullet speed is 2000 * delta in X direction.

Test result: softbody barely notices the bullet. Bullet does hit the softbody, I can see it in the debug view but softbody doesnt react to it

**Comment by Ughuuu** [comment]
Can you as well send a video of this? From screenshot seems like the softbody isnt constructed but its a voronoi diagram instead.

**Comment by Ughuuu** [comment]
Also if u can get on project discord, itll be easier to check whats wrong there.

**Comment by MrJox** [comment]
Scale indeed was one of the reasons it didnt work very well. I think node scale forfeits bone radius, which results in wrong behaviour when external rigid body collides into bones

**Comment by Ughuuu** [comment]
Added an example with apply_force in tutorial.gd file.
